basePath: '{{.BasePath}}'
host: '{{.Host}}'
info:
  contact: {}
  description: Go Backend Starter
  license: {}
  termsOfService: https://github.com/detectiveHLH/go-backend-starter
  title: Golang Gin API
  version: "1.0"
paths:
  /login:
    get:
      parameters:
      - description: username
        in: query
        name: username
        required: true
        type: string
      - description: password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
swagger: "2.0"
